<!doctype html>
<html lang="zh-cmn-Hans">
<head>
  <meta charset="utf-8">
  <title>Error | Node.js API &#x82F1;&#x6587;&#x6587;&#x6863;</title>
  <link rel="stylesheet" href="api.css-20170605.css" tppabs="http://nodejs.cn/static/api.css?20170605">
  <link rel="icon" sizes="32x32" type="image/png" href="/static/favicon.png">
</head>
<body class="alt apidoc lang_en" id="api-section-errors">
  <div id="content" class="clearfix">
    <div id="column2" class="interior">
      <div id="intro" class="interior">
        <a href="javascript:if(confirm('http://nodejs.cn/  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='http://nodejs.cn/'" tppabs="http://nodejs.cn/">
          Node.js &#x4E2D;&#x6587;&#x7F51;
        </a>
      </div>
      <ul>
<li><a class="nav-documentation" href="documentation-1.html" tppabs="http://nodejs.cn/api/en/documentation.html">About these Docs</a></li>
<li><a class="nav-synopsis" href="synopsis-1.html" tppabs="http://nodejs.cn/api/en/synopsis.html">Usage &amp; Example</a></li>
</ul>
<div class="line"></div>

<ul>
<li><a class="nav-assert" href="assert-1.html" tppabs="http://nodejs.cn/api/en/assert.html">Assertion Testing</a></li>
<li><a class="nav-async_hooks" href="async_hooks-1.html" tppabs="http://nodejs.cn/api/en/async_hooks.html">Async Hooks</a></li>
<li><a class="nav-buffer" href="buffer-1.html" tppabs="http://nodejs.cn/api/en/buffer.html">Buffer</a></li>
<li><a class="nav-addons" href="addons-1.html" tppabs="http://nodejs.cn/api/en/addons.html">C++ Addons</a></li>
<li><a class="nav-n-api" href="n-api-1.html" tppabs="http://nodejs.cn/api/en/n-api.html">C/C++ Addons - N-API</a></li>
<li><a class="nav-child_process" href="child_process-1.html" tppabs="http://nodejs.cn/api/en/child_process.html">Child Processes</a></li>
<li><a class="nav-cluster" href="cluster-1.html" tppabs="http://nodejs.cn/api/en/cluster.html">Cluster</a></li>
<li><a class="nav-cli" href="cli-1.html" tppabs="http://nodejs.cn/api/en/cli.html">Command Line Options</a></li>
<li><a class="nav-console" href="console-1.html" tppabs="http://nodejs.cn/api/en/console.html">Console</a></li>
<li><a class="nav-crypto" href="crypto-1.html" tppabs="http://nodejs.cn/api/en/crypto.html">Crypto</a></li>
<li><a class="nav-debugger" href="debugger-1.html" tppabs="http://nodejs.cn/api/en/debugger.html">Debugger</a></li>
<li><a class="nav-deprecations" href="deprecations-1.html" tppabs="http://nodejs.cn/api/en/deprecations.html">Deprecated APIs</a></li>
<li><a class="nav-dns" href="dns-1.html" tppabs="http://nodejs.cn/api/en/dns.html">DNS</a></li>
<li><a class="nav-domain" href="domain-1.html" tppabs="http://nodejs.cn/api/en/domain.html">Domain</a></li>
<li><a class="nav-errors active" href="errors-1.html" tppabs="http://nodejs.cn/api/en/errors.html">Errors</a></li>
<li><a class="nav-events" href="events-1.html" tppabs="http://nodejs.cn/api/en/events.html">Events</a></li>
<li><a class="nav-fs" href="fs-1.html" tppabs="http://nodejs.cn/api/en/fs.html">File System</a></li>
<li><a class="nav-globals" href="globals-1.html" tppabs="http://nodejs.cn/api/en/globals.html">Globals</a></li>
<li><a class="nav-http" href="http-1.html" tppabs="http://nodejs.cn/api/en/http.html">HTTP</a></li>
<li><a class="nav-https" href="https-1.html" tppabs="http://nodejs.cn/api/en/https.html">HTTPS</a></li>
<li><a class="nav-inspector" href="inspector-1.html" tppabs="http://nodejs.cn/api/en/inspector.html">Inspector</a></li>
<li><a class="nav-intl" href="intl-1.html" tppabs="http://nodejs.cn/api/en/intl.html">Internationalization</a></li>
<li><a class="nav-modules" href="modules-1.html" tppabs="http://nodejs.cn/api/en/modules.html">Modules</a></li>
<li><a class="nav-net" href="net-1.html" tppabs="http://nodejs.cn/api/en/net.html">Net</a></li>
<li><a class="nav-os" href="os-1.html" tppabs="http://nodejs.cn/api/en/os.html">OS</a></li>
<li><a class="nav-path" href="path-1.html" tppabs="http://nodejs.cn/api/en/path.html">Path</a></li>
<li><a class="nav-process" href="process-1.html" tppabs="http://nodejs.cn/api/en/process.html">Process</a></li>
<li><a class="nav-punycode" href="punycode-1.html" tppabs="http://nodejs.cn/api/en/punycode.html">Punycode</a></li>
<li><a class="nav-querystring" href="querystring-1.html" tppabs="http://nodejs.cn/api/en/querystring.html">Query Strings</a></li>
<li><a class="nav-readline" href="readline-1.html" tppabs="http://nodejs.cn/api/en/readline.html">Readline</a></li>
<li><a class="nav-repl" href="repl-1.html" tppabs="http://nodejs.cn/api/en/repl.html">REPL</a></li>
<li><a class="nav-stream" href="stream-1.html" tppabs="http://nodejs.cn/api/en/stream.html">Stream</a></li>
<li><a class="nav-string_decoder" href="string_decoder-1.html" tppabs="http://nodejs.cn/api/en/string_decoder.html">String Decoder</a></li>
<li><a class="nav-timers" href="timers-1.html" tppabs="http://nodejs.cn/api/en/timers.html">Timers</a></li>
<li><a class="nav-tls" href="tls-1.html" tppabs="http://nodejs.cn/api/en/tls.html">TLS/SSL</a></li>
<li><a class="nav-tracing" href="tracing-1.html" tppabs="http://nodejs.cn/api/en/tracing.html">Tracing</a></li>
<li><a class="nav-tty" href="tty-1.html" tppabs="http://nodejs.cn/api/en/tty.html">TTY</a></li>
<li><a class="nav-dgram" href="dgram-1.html" tppabs="http://nodejs.cn/api/en/dgram.html">UDP/Datagram</a></li>
<li><a class="nav-url" href="url-1.html" tppabs="http://nodejs.cn/api/en/url.html">URL</a></li>
<li><a class="nav-util" href="util-1.html" tppabs="http://nodejs.cn/api/en/util.html">Utilities</a></li>
<li><a class="nav-v8" href="v8-1.html" tppabs="http://nodejs.cn/api/en/v8.html">V8</a></li>
<li><a class="nav-vm" href="vm-1.html" tppabs="http://nodejs.cn/api/en/vm.html">VM</a></li>
<li><a class="nav-zlib" href="zlib-1.html" tppabs="http://nodejs.cn/api/en/zlib.html">ZLIB</a></li>
</ul>
<div class="line"></div>


    </div>

    <div id="column1" data-id="errors" class="interior">
      <header>
        <h1>Node.js v8.2.1 &#x82F1;&#x6587;&#x6587;&#x6863;</h1>
        <div id="gtoc">
          <p>
            <a href="index.html" tppabs="http://nodejs.cn/api/en/index.html" name="toc">&#x8FD4;&#x56DE;&#x6587;&#x6863;&#x9996;&#x9875;</a> |
            <!--<a href="all.html">View on single page</a> |-->
            <!--<a href="errors.json">View as JSON</a> |-->
            <a href="errors.html" tppabs="http://nodejs.cn/api/errors.html">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a>
          </p>
        </div>
        <hr>
      </header>

      <div id="toc">
        <h2>&#x76EE;&#x5F55;</h2>
        <ul>
<li><span class="stability_undefined"><a href="#errors_errors">Errors</a></span><ul>
<li><span class="stability_undefined"><a href="#errors_error_propagation_and_interception">Error Propagation and Interception</a></span><ul>
<li><span class="stability_undefined"><a href="#errors_node_js_style_callbacks">Node.js style callbacks</a></span></li>
</ul>
</li>
<li><span class="stability_undefined"><a href="#errors_class_error">Class: Error</a></span><ul>
<li><span class="stability_undefined"><a href="#errors_new_error_message">new Error(message)</a></span></li>
<li><span class="stability_undefined"><a href="#errors_error_capturestacktrace_targetobject_constructoropt">Error.captureStackTrace(targetObject[, constructorOpt])</a></span></li>
<li><span class="stability_undefined"><a href="#errors_error_stacktracelimit">Error.stackTraceLimit</a></span><ul>
<li><span class="stability_undefined"><a href="#errors_error_code">error.code</a></span></li>
<li><span class="stability_undefined"><a href="#errors_error_message">error.message</a></span></li>
</ul>
</li>
<li><span class="stability_undefined"><a href="#errors_error_stack">error.stack</a></span></li>
</ul>
</li>
<li><span class="stability_undefined"><a href="#errors_class_rangeerror">Class: RangeError</a></span></li>
<li><span class="stability_undefined"><a href="#errors_class_referenceerror">Class: ReferenceError</a></span></li>
<li><span class="stability_undefined"><a href="#errors_class_syntaxerror">Class: SyntaxError</a></span></li>
<li><span class="stability_undefined"><a href="#errors_class_typeerror">Class: TypeError</a></span></li>
<li><span class="stability_undefined"><a href="#errors_exceptions_vs_errors">Exceptions vs. Errors</a></span></li>
<li><span class="stability_undefined"><a href="#errors_system_errors">System Errors</a></span><ul>
<li><span class="stability_undefined"><a href="#errors_class_system_error">Class: System Error</a></span><ul>
<li><span class="stability_undefined"><a href="#errors_error_code_1">error.code</a></span></li>
<li><span class="stability_undefined"><a href="#errors_error_errno">error.errno</a></span></li>
<li><span class="stability_undefined"><a href="#errors_error_syscall">error.syscall</a></span></li>
<li><span class="stability_undefined"><a href="#errors_error_path">error.path</a></span></li>
<li><span class="stability_undefined"><a href="#errors_error_address">error.address</a></span></li>
<li><span class="stability_undefined"><a href="#errors_error_port">error.port</a></span></li>
</ul>
</li>
<li><span class="stability_undefined"><a href="#errors_common_system_errors">Common System Errors</a></span></li>
</ul>
</li>
<li><span class="stability_undefined"><a href="#errors_node_js_error_codes">Node.js Error Codes</a></span><ul>
<li><span class="stability_undefined"><a href="#errors_err_arg_not_iterable">ERR_ARG_NOT_ITERABLE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_falsy_value_rejection">ERR_FALSY_VALUE_REJECTION</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_arg_type">ERR_INVALID_ARG_TYPE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_callback">ERR_INVALID_CALLBACK</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_file_url_host">ERR_INVALID_FILE_URL_HOST</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_file_url_path">ERR_INVALID_FILE_URL_PATH</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_handle_type">ERR_INVALID_HANDLE_TYPE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_opt_value">ERR_INVALID_OPT_VALUE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_sync_fork_input">ERR_INVALID_SYNC_FORK_INPUT</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_this">ERR_INVALID_THIS</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_tuple">ERR_INVALID_TUPLE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_url">ERR_INVALID_URL</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_invalid_url_scheme">ERR_INVALID_URL_SCHEME</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_ipc_channel_closed">ERR_IPC_CHANNEL_CLOSED</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_ipc_disconnected">ERR_IPC_DISCONNECTED</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_ipc_one_pipe">ERR_IPC_ONE_PIPE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_ipc_sync_fork">ERR_IPC_SYNC_FORK</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_missing_args">ERR_MISSING_ARGS</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_socket_already_bound">ERR_SOCKET_ALREADY_BOUND</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_socket_bad_port">ERR_SOCKET_BAD_PORT</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_socket_bad_type">ERR_SOCKET_BAD_TYPE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_socket_cannot_send">ERR_SOCKET_CANNOT_SEND</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_socket_dgram_not_running">ERR_SOCKET_DGRAM_NOT_RUNNING</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_stderr_close">ERR_STDERR_CLOSE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_stdout_close">ERR_STDOUT_CLOSE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_unknown_builtin_module">ERR_UNKNOWN_BUILTIN_MODULE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_unknown_signal">ERR_UNKNOWN_SIGNAL</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_unknown_stdin_type">ERR_UNKNOWN_STDIN_TYPE</a></span></li>
<li><span class="stability_undefined"><a href="#errors_err_unknown_stream_type">ERR_UNKNOWN_STREAM_TYPE</a></span></li>
</ul>
</li>
</ul>
</li>
</ul>

      </div>

      <div id="apicontent">
        <h1>Errors<span><a class="mark" href="#errors_errors" id="errors_errors">#</a></span></h1><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_errors" tppabs="http://nodejs.cn/api/errors.html#errors_errors">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<!--type=misc-->
<p>Applications running in Node.js will generally experience four categories of
errors:</p>
<ul>
<li>Standard JavaScript errors such as:<ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError" class="type">&lt;EvalError&gt;</a> : thrown when a call to <code>eval()</code> fails.</li>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError" class="type">&lt;SyntaxError&gt;</a> : thrown in response to improper JavaScript language
syntax.</li>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError" class="type">&lt;RangeError&gt;</a> : thrown when a value is not within an expected range</li>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError" class="type">&lt;ReferenceError&gt;</a> : thrown when using undefined variables</li>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError" class="type">&lt;TypeError&gt;</a> : thrown when passing arguments of the wrong type</li>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError" class="type">&lt;URIError&gt;</a> : thrown when a global URI handling function is misused.</li>
</ul>
</li>
<li>System errors triggered by underlying operating system constraints such
as attempting to open a file that does not exist, attempting to send data
over a closed socket, etc;</li>
<li>And User-specified errors triggered by application code.</li>
<li>Assertion Errors are a special class of error that can be triggered whenever
Node.js detects an exceptional logic violation that should never occur. These
are raised typically by the <code>assert</code> module.</li>
</ul>
<p>All JavaScript and System errors raised by Node.js inherit from, or are
instances of, the standard JavaScript <a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error" class="type">&lt;Error&gt;</a> class and are guaranteed
to provide <em>at least</em> the properties available on that class.</p>
<h2>Error Propagation and Interception<span><a class="mark" href="#errors_error_propagation_and_interception" id="errors_error_propagation_and_interception">#</a></span></h2><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_propagation_and_interception" tppabs="http://nodejs.cn/api/errors.html#errors_error_propagation_and_interception">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<!--type=misc-->
<p>Node.js supports several mechanisms for propagating and handling errors that
occur while an application is running. How these errors are reported and
handled depends entirely on the type of Error and the style of the API that is
called.</p>
<p>All JavaScript errors are handled as exceptions that <em>immediately</em> generate
and throw an error using the standard JavaScript <code>throw</code> mechanism. These
are handled using the <a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch"><code>try / catch</code> construct</a> provided by the
JavaScript language.</p>
<pre><code class="lang-js">// Throws with a ReferenceError because z is undefined
try {
  const m = 1;
  const n = m + z;
} catch (err) {
  // Handle the error here.
}
</code></pre>
<p>Any use of the JavaScript <code>throw</code> mechanism will raise an exception that
<em>must</em> be handled using <code>try / catch</code> or the Node.js process will exit
immediately.</p>
<p>With few exceptions, <em>Synchronous</em> APIs (any blocking method that does not
accept a <code>callback</code> function, such as <a href="fs-1.html#fs_fs_readfilesync_path_options" tppabs="http://nodejs.cn/api/en/fs.html#fs_fs_readfilesync_path_options"><code>fs.readFileSync</code></a>), will use <code>throw</code>
to report errors.</p>
<p>Errors that occur within <em>Asynchronous APIs</em> may be reported in multiple ways:</p>
<ul>
<li>Most asynchronous methods that accept a <code>callback</code> function will accept an
<code>Error</code> object passed as the first argument to that function. If that first
argument is not <code>null</code> and is an instance of <code>Error</code>, then an error occurred
that should be handled.</li>
</ul>
<!-- eslint-disable no-useless-return -->
<pre><code class="lang-js">  const fs = require(&apos;fs&apos;);
  fs.readFile(&apos;a file that does not exist&apos;, (err, data) =&gt; {
    if (err) {
      console.error(&apos;There was an error reading the file!&apos;, err);
      return;
    }
    // Otherwise handle the data
  });
</code></pre>
<ul>
<li><p>When an asynchronous method is called on an object that is an <code>EventEmitter</code>,
errors can be routed to that object&apos;s <code>&apos;error&apos;</code> event.</p>
<pre><code class="lang-js">const net = require(&apos;net&apos;);
const connection = net.connect(&apos;localhost&apos;);

// Adding an &apos;error&apos; event handler to a stream:
connection.on(&apos;error&apos;, (err) =&gt; {
  // If the connection is reset by the server, or if it can&apos;t
  // connect at all, or on any sort of error encountered by
  // the connection, the error will be sent here.
  console.error(err);
});

connection.pipe(process.stdout);
</code></pre>
</li>
<li><p>A handful of typically asynchronous methods in the Node.js API may still
use the <code>throw</code> mechanism to raise exceptions that must be handled using
<code>try / catch</code>. There is no comprehensive list of such methods; please
refer to the documentation of each method to determine the appropriate
error handling mechanism required.</p>
</li>
</ul>
<p>The use of the <code>&apos;error&apos;</code> event mechanism is most common for <a href="stream-1.html" tppabs="http://nodejs.cn/api/en/stream.html">stream-based</a>
and <a href="events-1.html#events_class_eventemitter" tppabs="http://nodejs.cn/api/en/events.html#events_class_eventemitter">event emitter-based</a> APIs, which themselves represent a series of
asynchronous operations over time (as opposed to a single operation that may
pass or fail).</p>
<p>For <em>all</em> <code>EventEmitter</code> objects, if an <code>&apos;error&apos;</code> event handler is not
provided, the error will be thrown, causing the Node.js process to report an
unhandled exception and  crash unless either: The <a href="domain-1.html" tppabs="http://nodejs.cn/api/en/domain.html"><code>domain</code></a> module is
used appropriately or a handler has been registered for the
<a href="process-1.html#process_event_uncaughtexception" tppabs="http://nodejs.cn/api/en/process.html#process_event_uncaughtexception"><code>process.on(&apos;uncaughtException&apos;)</code></a> event.</p>
<pre><code class="lang-js">const EventEmitter = require(&apos;events&apos;);
const ee = new EventEmitter();

setImmediate(() =&gt; {
  // This will crash the process because no &apos;error&apos; event
  // handler has been added.
  ee.emit(&apos;error&apos;, new Error(&apos;This will crash&apos;));
});
</code></pre>
<p>Errors generated in this way <em>cannot</em> be intercepted using <code>try / catch</code> as
they are thrown <em>after</em> the calling code has already exited.</p>
<p>Developers must refer to the documentation for each method to determine
exactly how errors raised by those methods are propagated.</p>
<h3>Node.js style callbacks<span><a class="mark" href="#errors_node_js_style_callbacks" id="errors_node_js_style_callbacks">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_node_js_style_callbacks" tppabs="http://nodejs.cn/api/errors.html#errors_node_js_style_callbacks">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<!--type=misc-->
<p>Most asynchronous methods exposed by the Node.js core API follow an idiomatic
pattern  referred to as a &quot;Node.js style callback&quot;. With this pattern, a
callback function is passed to the method as an argument. When the operation
either completes or an error is raised, the callback function is called with
the Error object (if any) passed as the first argument. If no error was raised,
the first argument will be passed as <code>null</code>.</p>
<pre><code class="lang-js">const fs = require(&apos;fs&apos;);

function nodeStyleCallback(err, data) {
  if (err) {
    console.error(&apos;There was an error&apos;, err);
    return;
  }
  console.log(data);
}

fs.readFile(&apos;/some/file/that/does-not-exist&apos;, nodeStyleCallback);
fs.readFile(&apos;/some/file/that/does-exist&apos;, nodeStyleCallback);
</code></pre>
<p>The JavaScript <code>try / catch</code> mechanism <strong>cannot</strong> be used to intercept errors
generated by asynchronous APIs.  A common mistake for beginners is to try to
use <code>throw</code> inside a Node.js style callback:</p>
<pre><code class="lang-js">// THIS WILL NOT WORK:
const fs = require(&apos;fs&apos;);

try {
  fs.readFile(&apos;/some/file/that/does-not-exist&apos;, (err, data) =&gt; {
    // mistaken assumption: throwing here...
    if (err) {
      throw err;
    }
  });
} catch (err) {
  // This will not catch the throw!
  console.error(err);
}
</code></pre>
<p>This will not work because the callback function passed to <code>fs.readFile()</code> is
called asynchronously. By the time the callback has been called, the
surrounding code (including the <code>try { } catch (err) { }</code> block will have
already exited. Throwing an error inside the callback <strong>can crash the Node.js
process</strong> in most cases. If <a href="domain-1.html" tppabs="http://nodejs.cn/api/en/domain.html">domains</a> are enabled, or a handler has been
registered with <code>process.on(&apos;uncaughtException&apos;)</code>, such errors can be
intercepted.</p>
<h2>Class: Error<span><a class="mark" href="#errors_class_error" id="errors_class_error">#</a></span></h2><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_class_error" tppabs="http://nodejs.cn/api/errors.html#errors_class_error">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<!--type=class-->
<p>A generic JavaScript <code>Error</code> object that does not denote any specific
circumstance of why the error occurred. <code>Error</code> objects capture a &quot;stack trace&quot;
detailing the point in the code at which the <code>Error</code> was instantiated, and may
provide a text description of the error.</p>
<p>All errors generated by Node.js, including all System and JavaScript errors,
will either be instances of, or inherit from, the <code>Error</code> class.</p>
<h3>new Error(message)<span><a class="mark" href="#errors_new_error_message" id="errors_new_error_message">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_new_error_message" tppabs="http://nodejs.cn/api/errors.html#errors_new_error_message">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><code>message</code> <a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type">&lt;string&gt;</a></li>
</ul>
</div><p>Creates a new <code>Error</code> object and sets the <code>error.message</code> property to the
provided text message. If an object is passed as <code>message</code>, the text message
is generated by calling <code>message.toString()</code>. The <code>error.stack</code> property will
represent the point in the code at which <code>new Error()</code> was called. Stack traces
are dependent on <a href="javascript:if(confirm('https://github.com/v8/v8/wiki/Stack-Trace-API  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://github.com/v8/v8/wiki/Stack-Trace-API'" tppabs="https://github.com/v8/v8/wiki/Stack-Trace-API">V8&apos;s stack trace API</a>. Stack traces extend only to either
(a) the beginning of  <em>synchronous code execution</em>, or (b) the number of frames
given by the property <code>Error.stackTraceLimit</code>, whichever is smaller.</p>
<h3>Error.captureStackTrace(targetObject[, constructorOpt])<span><a class="mark" href="#errors_error_capturestacktrace_targetobject_constructoropt" id="errors_error_capturestacktrace_targetobject_constructoropt">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_capturestacktrace_targetobject_constructoropt" tppabs="http://nodejs.cn/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><code>targetObject</code> <a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object" class="type">&lt;Object&gt;</a></li>
<li><code>constructorOpt</code> <a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function" class="type">&lt;Function&gt;</a></li>
</ul>
</div><p>Creates a <code>.stack</code> property on <code>targetObject</code>, which when accessed returns
a string representing the location in the code at which
<code>Error.captureStackTrace()</code> was called.</p>
<pre><code class="lang-js">const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // similar to `new Error().stack`
</code></pre>
<p>The first line of the trace will be prefixed with <code>${myObject.name}: ${myObject.message}</code>.</p>
<p>The optional <code>constructorOpt</code> argument accepts a function. If given, all frames
above <code>constructorOpt</code>, including <code>constructorOpt</code>, will be omitted from the
generated stack trace.</p>
<p>The <code>constructorOpt</code> argument is useful for hiding implementation
details of error generation from an end user. For instance:</p>
<pre><code class="lang-js">function MyError() {
  Error.captureStackTrace(this, MyError);
}

// Without passing MyError to captureStackTrace, the MyError
// frame would show up in the .stack property. By passing
// the constructor, we omit that frame, and retain all frames below it.
new MyError().stack;
</code></pre>
<h3>Error.stackTraceLimit<span><a class="mark" href="#errors_error_stacktracelimit" id="errors_error_stacktracelimit">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_stacktracelimit" tppabs="http://nodejs.cn/api/errors.html#errors_error_stacktracelimit">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type">&lt;number&gt;</a></li>
</ul>
</div><p>The <code>Error.stackTraceLimit</code> property specifies the number of stack frames
collected by a stack trace (whether generated by <code>new Error().stack</code> or
<code>Error.captureStackTrace(obj)</code>).</p>
<p>The default value is <code>10</code> but may be set to any valid JavaScript number. Changes
will affect any stack trace captured <em>after</em> the value has been changed.</p>
<p>If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.</p>
<h4>error.code<span><a class="mark" href="#errors_error_code" id="errors_error_code">#</a></span></h4><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_code" tppabs="http://nodejs.cn/api/errors.html#errors_error_code">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type">&lt;string&gt;</a></li>
</ul>
</div><p>The <code>error.code</code> property is a string label that identifies the kind of error.
See <a href="#nodejs-error-codes">Node.js Error Codes</a> for details about specific codes.</p>
<h4>error.message<span><a class="mark" href="#errors_error_message" id="errors_error_message">#</a></span></h4><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_message" tppabs="http://nodejs.cn/api/errors.html#errors_error_message">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type">&lt;string&gt;</a></li>
</ul>
</div><p>The <code>error.message</code> property is the string description of the error as set by
calling <code>new Error(message)</code>. The <code>message</code> passed to the constructor will also
appear in the first line of the stack trace of the <code>Error</code>, however changing
this property after the <code>Error</code> object is created <em>may not</em> change the first
line of the stack trace (for example, when <code>error.stack</code> is read before this
property is changed).</p>
<pre><code class="lang-js">const err = new Error(&apos;The message&apos;);
console.error(err.message);
// Prints: The message
</code></pre>
<h3>error.stack<span><a class="mark" href="#errors_error_stack" id="errors_error_stack">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_stack" tppabs="http://nodejs.cn/api/errors.html#errors_error_stack">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type">&lt;string&gt;</a></li>
</ul>
</div><p>The <code>error.stack</code> property is a string describing the point in the code at which
the <code>Error</code> was instantiated.</p>
<p>For example:</p>
<pre><code class="lang-txt">Error: Things keep happening!
   at /home/gbusey/file.js:525:2
   at Frobnicator.refrobulate (/home/gbusey/business-logic.js:424:21)
   at Actor.&lt;anonymous&gt; (/home/gbusey/actors.js:400:8)
   at increaseSynergy (/home/gbusey/actors.js:701:6)
</code></pre>
<p>The first line is formatted as <code>&lt;error class name&gt;: &lt;error message&gt;</code>, and
is followed by a series of stack frames (each line beginning with &quot;at &quot;).
Each frame describes a call site within the code that lead to the error being
generated. V8 attempts to display a name for each function (by variable name,
function name, or object method name), but occasionally it will not be able to
find a suitable name. If V8 cannot determine a name for the function, only
location information will be displayed for that frame. Otherwise, the
determined function name will be displayed with location information appended
in parentheses.</p>
<p>It is important to note that frames are <strong>only</strong> generated for JavaScript
functions. If, for example, execution synchronously passes through a C++ addon
function called <code>cheetahify</code>, which itself calls a JavaScript function, the
frame representing the <code>cheetahify</code> call will <strong>not</strong> be present in the stack
traces:</p>
<pre><code class="lang-js">const cheetahify = require(&apos;./native-binding.node&apos;);

function makeFaster() {
  // cheetahify *synchronously* calls speedy.
  cheetahify(function speedy() {
    throw new Error(&apos;oh no!&apos;);
  });
}

makeFaster();
// will throw:
//   /home/gbusey/file.js:6
//       throw new Error(&apos;oh no!&apos;);
//           ^
//   Error: oh no!
//       at speedy (/home/gbusey/file.js:6:11)
//       at makeFaster (/home/gbusey/file.js:5:3)
//       at Object.&lt;anonymous&gt; (/home/gbusey/file.js:10:1)
//       at Module._compile (module.js:456:26)
//       at Object.Module._extensions..js (module.js:474:10)
//       at Module.load (module.js:356:32)
//       at Function.Module._load (module.js:312:12)
//       at Function.Module.runMain (module.js:497:10)
//       at startup (node.js:119:16)
//       at node.js:906:3
</code></pre>
<p>The location information will be one of:</p>
<ul>
<li><code>native</code>, if the frame represents a call internal to V8 (as in <code>[].forEach</code>).</li>
<li><code>plain-filename.js:line:column</code>, if the frame represents a call internal
 to Node.js.</li>
<li><code>/absolute/path/to/file.js:line:column</code>, if the frame represents a call in
a user program, or its dependencies.</li>
</ul>
<p>The string representing the stack trace is lazily generated when the
<code>error.stack</code> property is <strong>accessed</strong>.</p>
<p>The number of frames captured by the stack trace is bounded by the smaller of
<code>Error.stackTraceLimit</code> or the number of available frames on the current event
loop tick.</p>
<p>System-level errors are generated as augmented <code>Error</code> instances, which are
detailed <a href="#errors_system_errors">here</a>.</p>
<h2>Class: RangeError<span><a class="mark" href="#errors_class_rangeerror" id="errors_class_rangeerror">#</a></span></h2><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_class_rangeerror" tppabs="http://nodejs.cn/api/errors.html#errors_class_rangeerror">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>A subclass of <code>Error</code> that indicates that a provided argument was not within the
set or range of acceptable values for a function; whether that is a numeric
range, or outside the set of options for a given function parameter.</p>
<p>For example:</p>
<pre><code class="lang-js">require(&apos;net&apos;).connect(-1);
// throws &quot;RangeError: &quot;port&quot; option should be &gt;= 0 and &lt; 65536: -1&quot;
</code></pre>
<p>Node.js will generate and throw <code>RangeError</code> instances <em>immediately</em> as a form
of argument validation.</p>
<h2>Class: ReferenceError<span><a class="mark" href="#errors_class_referenceerror" id="errors_class_referenceerror">#</a></span></h2><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_class_referenceerror" tppabs="http://nodejs.cn/api/errors.html#errors_class_referenceerror">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>A subclass of <code>Error</code> that indicates that an attempt is being made to access a
variable that is not defined. Such errors commonly indicate typos in code, or
an otherwise broken program.</p>
<p>While client code may generate and propagate these errors, in practice, only V8
will do so.</p>
<pre><code class="lang-js">doesNotExist;
// throws ReferenceError, doesNotExist is not a variable in this program.
</code></pre>
<p>Unless an application is dynamically generating and running code,
<code>ReferenceError</code> instances should always be considered a bug in the code
or its dependencies.</p>
<h2>Class: SyntaxError<span><a class="mark" href="#errors_class_syntaxerror" id="errors_class_syntaxerror">#</a></span></h2><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_class_syntaxerror" tppabs="http://nodejs.cn/api/errors.html#errors_class_syntaxerror">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>A subclass of <code>Error</code> that indicates that a program is not valid JavaScript.
These errors may only be generated and propagated as a result of code
evaluation. Code evaluation may happen as a result of <code>eval</code>, <code>Function</code>,
<code>require</code>, or <a href="vm-1.html" tppabs="http://nodejs.cn/api/en/vm.html">vm</a>. These errors are almost always indicative of a broken
program.</p>
<pre><code class="lang-js">try {
  require(&apos;vm&apos;).runInThisContext(&apos;binary ! isNotOk&apos;);
} catch (err) {
  // err will be a SyntaxError
}
</code></pre>
<p><code>SyntaxError</code> instances are unrecoverable in the context that created them &#x2013;
they may only be caught by other contexts.</p>
<h2>Class: TypeError<span><a class="mark" href="#errors_class_typeerror" id="errors_class_typeerror">#</a></span></h2><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_class_typeerror" tppabs="http://nodejs.cn/api/errors.html#errors_class_typeerror">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>A subclass of <code>Error</code> that indicates that a provided argument is not an
allowable type. For example, passing a function to a parameter which expects a
string would be considered a TypeError.</p>
<pre><code class="lang-js">require(&apos;url&apos;).parse(() =&gt; { });
// throws TypeError, since it expected a string
</code></pre>
<p>Node.js will generate and throw <code>TypeError</code> instances <em>immediately</em> as a form
of argument validation.</p>
<h2>Exceptions vs. Errors<span><a class="mark" href="#errors_exceptions_vs_errors" id="errors_exceptions_vs_errors">#</a></span></h2><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_exceptions_vs_errors" tppabs="http://nodejs.cn/api/errors.html#errors_exceptions_vs_errors">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<!--type=misc-->
<p>A JavaScript exception is a value that is thrown as a result of an invalid
operation or as the target of a <code>throw</code> statement. While it is not required
that these values are instances of <code>Error</code> or classes which inherit from
<code>Error</code>, all exceptions thrown by Node.js or the JavaScript runtime <em>will</em> be
instances of Error.</p>
<p>Some exceptions are <em>unrecoverable</em> at the JavaScript layer. Such exceptions
will <em>always</em> cause the Node.js process to crash. Examples include <code>assert()</code>
checks or <code>abort()</code> calls in the C++ layer.</p>
<h2>System Errors<span><a class="mark" href="#errors_system_errors" id="errors_system_errors">#</a></span></h2><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_system_errors" tppabs="http://nodejs.cn/api/errors.html#errors_system_errors">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>System errors are generated when exceptions occur within the program&apos;s
runtime environment. Typically, these are operational errors that occur
when an application violates an operating system constraint such as attempting
to read a file that does not exist or when the user does not have sufficient
permissions.</p>
<p>System errors are typically generated at the syscall level: an exhaustive list
of error codes and their meanings is available by running <code>man 2 intro</code> or
<code>man 3 errno</code> on most Unices; or <a href="javascript:if(confirm('http://man7.org/linux/man-pages/man3/errno.3.html  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='http://man7.org/linux/man-pages/man3/errno.3.html'" tppabs="http://man7.org/linux/man-pages/man3/errno.3.html">online</a>.</p>
<p>In Node.js, system errors are represented as augmented <code>Error</code> objects with
added properties.</p>
<h3>Class: System Error<span><a class="mark" href="#errors_class_system_error" id="errors_class_system_error">#</a></span></h3>
<h4>error.code<span><a class="mark" href="#errors_error_code_1" id="errors_error_code_1">#</a></span></h4><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_code_1" tppabs="http://nodejs.cn/api/errors.html#errors_error_code_1">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type">&lt;string&gt;</a></li>
</ul>
</div><p>The <code>error.code</code> property is a string representing the error code, which is
typically <code>E</code> followed by a sequence of capital letters.</p>
<h4>error.errno<span><a class="mark" href="#errors_error_errno" id="errors_error_errno">#</a></span></h4><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_errno" tppabs="http://nodejs.cn/api/errors.html#errors_error_errno">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type">&lt;string&gt;</a> | <a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type">&lt;number&gt;</a></li>
</ul>
</div><p>The <code>error.errno</code> property is a number or a string.
The number is a <strong>negative</strong> value which corresponds to the error code defined
in <a href="javascript:if(confirm('http://docs.libuv.org/en/v1.x/errors.html  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='http://docs.libuv.org/en/v1.x/errors.html'" tppabs="http://docs.libuv.org/en/v1.x/errors.html"><code>libuv Error handling</code></a>. See uv-errno.h header file
(<code>deps/uv/include/uv-errno.h</code> in the Node.js source tree) for details. In case
of a string, it is the same as <code>error.code</code>.</p>
<h4>error.syscall<span><a class="mark" href="#errors_error_syscall" id="errors_error_syscall">#</a></span></h4><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_syscall" tppabs="http://nodejs.cn/api/errors.html#errors_error_syscall">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type">&lt;string&gt;</a></li>
</ul>
</div><p>The <code>error.syscall</code> property is a string describing the <a href="javascript:if(confirm('http://man7.org/linux/man-pages/man2/syscall.2.html  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='http://man7.org/linux/man-pages/man2/syscall.2.html'" tppabs="http://man7.org/linux/man-pages/man2/syscall.2.html">syscall</a> that failed.</p>
<h4>error.path<span><a class="mark" href="#errors_error_path" id="errors_error_path">#</a></span></h4><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_path" tppabs="http://nodejs.cn/api/errors.html#errors_error_path">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type">&lt;string&gt;</a></li>
</ul>
</div><p>When present (e.g. in <code>fs</code> or <code>child_process</code>), the <code>error.path</code> property is a
string containing a relevant invalid pathname.</p>
<h4>error.address<span><a class="mark" href="#errors_error_address" id="errors_error_address">#</a></span></h4><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_address" tppabs="http://nodejs.cn/api/errors.html#errors_error_address">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type">&lt;string&gt;</a></li>
</ul>
</div><p>When present (e.g. in <code>net</code> or <code>dgram</code>), the <code>error.address</code> property is a
string describing the address to which the connection failed.</p>
<h4>error.port<span><a class="mark" href="#errors_error_port" id="errors_error_port">#</a></span></h4><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_error_port" tppabs="http://nodejs.cn/api/errors.html#errors_error_port">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<div class="signature"><ul>
<li><a href="javascript:if(confirm('https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type'" tppabs="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type">&lt;number&gt;</a></li>
</ul>
</div><p>When present (e.g. in <code>net</code> or <code>dgram</code>), the <code>error.port</code> property is a number
representing the connection&apos;s port that is not available.</p>
<h3>Common System Errors<span><a class="mark" href="#errors_common_system_errors" id="errors_common_system_errors">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_common_system_errors" tppabs="http://nodejs.cn/api/errors.html#errors_common_system_errors">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>This list is <strong>not exhaustive</strong>, but enumerates many of the common system
errors encountered when writing a Node.js program. An exhaustive list may be
found <a href="javascript:if(confirm('http://man7.org/linux/man-pages/man3/errno.3.html  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='http://man7.org/linux/man-pages/man3/errno.3.html'" tppabs="http://man7.org/linux/man-pages/man3/errno.3.html">here</a>.</p>
<ul>
<li><p><code>EACCES</code> (Permission denied): An attempt was made to access a file in a way
forbidden by its file access permissions.</p>
</li>
<li><p><code>EADDRINUSE</code> (Address already in use):  An attempt to bind a server
(<a href="net-1.html" tppabs="http://nodejs.cn/api/en/net.html"><code>net</code></a>, <a href="http-1.html" tppabs="http://nodejs.cn/api/en/http.html"><code>http</code></a>, or <a href="https-1.html" tppabs="http://nodejs.cn/api/en/https.html"><code>https</code></a>) to a local address failed due to
another server on the local system already occupying that address.</p>
</li>
<li><p><code>ECONNREFUSED</code> (Connection refused): No connection could be made because the
target machine actively refused it. This usually results from trying to
connect to a service that is inactive on the foreign host.</p>
</li>
<li><p><code>ECONNRESET</code> (Connection reset by peer): A connection was forcibly closed by
a peer. This normally results from a loss of the connection on the remote
socket due to a timeout or reboot. Commonly encountered via the <a href="http-1.html" tppabs="http://nodejs.cn/api/en/http.html"><code>http</code></a>
and <a href="net-1.html" tppabs="http://nodejs.cn/api/en/net.html"><code>net</code></a> modules.</p>
</li>
<li><p><code>EEXIST</code> (File exists): An existing file was the target of an operation that
required that the target not exist.</p>
</li>
<li><p><code>EISDIR</code> (Is a directory): An operation expected a file, but the given
pathname was a directory.</p>
</li>
<li><p><code>EMFILE</code> (Too many open files in system): Maximum number of
<a href="javascript:if(confirm('https://en.wikipedia.org/wiki/File_descriptor  \n\n该文件无法用 Teleport Ultra 下载, 因为 它是一个域或路径外部被设置为它的启始地址的地址。  \n\n你想在服务器上打开它?'))window.location='https://en.wikipedia.org/wiki/File_descriptor'" tppabs="https://en.wikipedia.org/wiki/File_descriptor">file descriptors</a> allowable on the system has been reached, and
requests for another descriptor cannot be fulfilled until at least one
has been closed. This is encountered when opening many files at once in
parallel, especially on systems (in particular, macOS) where there is a low
file descriptor limit for processes. To remedy a low limit, run
<code>ulimit -n 2048</code> in the same shell that will run the Node.js process.</p>
</li>
<li><p><code>ENOENT</code> (No such file or directory): Commonly raised by <a href="fs-1.html" tppabs="http://nodejs.cn/api/en/fs.html"><code>fs</code></a> operations
to indicate that a component of the specified pathname does not exist -- no
entity (file or directory) could be found by the given path.</p>
</li>
<li><p><code>ENOTDIR</code> (Not a directory): A component of the given pathname existed, but
was not a directory as expected. Commonly raised by <a href="fs-1.html#fs_fs_readdir_path_options_callback" tppabs="http://nodejs.cn/api/en/fs.html#fs_fs_readdir_path_options_callback"><code>fs.readdir</code></a>.</p>
</li>
<li><p><code>ENOTEMPTY</code> (Directory not empty): A directory with entries was the target
of an operation that requires an empty directory -- usually <a href="fs-1.html#fs_fs_unlink_path_callback" tppabs="http://nodejs.cn/api/en/fs.html#fs_fs_unlink_path_callback"><code>fs.unlink</code></a>.</p>
</li>
<li><p><code>EPERM</code> (Operation not permitted): An attempt was made to perform an
operation that requires elevated privileges.</p>
</li>
<li><p><code>EPIPE</code> (Broken pipe): A write on a pipe, socket, or FIFO for which there is
no process to read the data. Commonly encountered at the <a href="net-1.html" tppabs="http://nodejs.cn/api/en/net.html"><code>net</code></a> and
<a href="http-1.html" tppabs="http://nodejs.cn/api/en/http.html"><code>http</code></a> layers, indicative that the remote side of the stream being
written to has been closed.</p>
</li>
<li><p><code>ETIMEDOUT</code> (Operation timed out): A connect or send request failed because
the connected party did not properly respond after a period of time. Usually
encountered by <a href="http-1.html" tppabs="http://nodejs.cn/api/en/http.html"><code>http</code></a> or <a href="net-1.html" tppabs="http://nodejs.cn/api/en/net.html"><code>net</code></a> -- often a sign that a <code>socket.end()</code>
was not properly called.</p>
</li>
</ul>
<p><a id="nodejs-error-codes"></a></p>
<h2>Node.js Error Codes<span><a class="mark" href="#errors_node_js_error_codes" id="errors_node_js_error_codes">#</a></span></h2><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_node_js_error_codes" tppabs="http://nodejs.cn/api/errors.html#errors_node_js_error_codes">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p><a id="ERR_ARG_NOT_ITERABLE"></a></p>
<h3>ERR_ARG_NOT_ITERABLE<span><a class="mark" href="#errors_err_arg_not_iterable" id="errors_err_arg_not_iterable">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_arg_not_iterable" tppabs="http://nodejs.cn/api/errors.html#errors_err_arg_not_iterable">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used generically to identify that an iterable argument (i.e. a value that works
with <code>for...of</code> loops) is required, but not provided to a Node.js API.</p>
<p><a id="ERR_FALSY_VALUE_REJECTION"></a></p>
<h3>ERR_FALSY_VALUE_REJECTION<span><a class="mark" href="#errors_err_falsy_value_rejection" id="errors_err_falsy_value_rejection">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_falsy_value_rejection" tppabs="http://nodejs.cn/api/errors.html#errors_err_falsy_value_rejection">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used by the <code>util.callbackify()</code> API when a callbackified <code>Promise</code> is rejected
with a falsy value (e.g. <code>null</code>).</p>
<p><a id="ERR_INVALID_ARG_TYPE"></a></p>
<h3>ERR_INVALID_ARG_TYPE<span><a class="mark" href="#errors_err_invalid_arg_type" id="errors_err_invalid_arg_type">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_arg_type" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_arg_type">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used generically to identify that an argument of the wrong type has been passed
to a Node.js API.</p>
<p><a id="ERR_INVALID_CALLBACK"></a></p>
<h3>ERR_INVALID_CALLBACK<span><a class="mark" href="#errors_err_invalid_callback" id="errors_err_invalid_callback">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_callback" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_callback">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used generically to identify that a callback function is required and has not
been provided to a Node.js API.</p>
<p><a id="ERR_INVALID_FILE_URL_HOST"></a></p>
<h3>ERR_INVALID_FILE_URL_HOST<span><a class="mark" href="#errors_err_invalid_file_url_host" id="errors_err_invalid_file_url_host">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_file_url_host" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_file_url_host">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when a Node.js API that consumes <code>file:</code> URLs (such as certain functions in
the <a href="fs-1.html" tppabs="http://nodejs.cn/api/en/fs.html"><code>fs</code></a> module) encounters a file URL with an incompatible host. Currently,
this situation can only occur on Unix-like systems, where only <code>localhost</code> or an
empty host is supported.</p>
<p><a id="ERR_INVALID_FILE_URL_PATH"></a></p>
<h3>ERR_INVALID_FILE_URL_PATH<span><a class="mark" href="#errors_err_invalid_file_url_path" id="errors_err_invalid_file_url_path">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_file_url_path" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_file_url_path">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when a Node.js API that consumes <code>file:</code> URLs (such as certain
functions in the <a href="fs-1.html" tppabs="http://nodejs.cn/api/en/fs.html"><code>fs</code></a> module) encounters a file URL with an incompatible
path. The exact semantics for determining whether a path can be used is
platform-dependent.</p>
<p><a id="ERR_INVALID_HANDLE_TYPE"></a></p>
<h3>ERR_INVALID_HANDLE_TYPE<span><a class="mark" href="#errors_err_invalid_handle_type" id="errors_err_invalid_handle_type">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_handle_type" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_handle_type">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an attempt is made to send an unsupported &quot;handle&quot; over an IPC
communication channel to a child process. See <a href="child_process-1.html#child_process_child_send_message_sendhandle_options_callback" tppabs="http://nodejs.cn/api/en/child_process.html#child_process_child_send_message_sendhandle_options_callback"><code>child.send()</code></a> and
<a href="process-1.html#process_process_send_message_sendhandle_options_callback" tppabs="http://nodejs.cn/api/en/process.html#process_process_send_message_sendhandle_options_callback"><code>process.send()</code></a> for more information.</p>
<p><a id="ERR_INVALID_OPT_VALUE"></a></p>
<h3>ERR_INVALID_OPT_VALUE<span><a class="mark" href="#errors_err_invalid_opt_value" id="errors_err_invalid_opt_value">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_opt_value" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_opt_value">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used generically to identify when an invalid or unexpected value has been
passed in an options object.</p>
<p><a id="ERR_INVALID_SYNC_FORK_INPUT"></a></p>
<h3>ERR_INVALID_SYNC_FORK_INPUT<span><a class="mark" href="#errors_err_invalid_sync_fork_input" id="errors_err_invalid_sync_fork_input">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_sync_fork_input" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_sync_fork_input">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when a <code>Buffer</code>, <code>Uint8Array</code> or <code>string</code> is provided as stdio input to a
synchronous fork. See the documentation for the
<a href="child_process-1.html" tppabs="http://nodejs.cn/api/en/child_process.html"><code>child_process</code></a> module for more information.</p>
<p><a id="ERR_INVALID_THIS"></a></p>
<h3>ERR_INVALID_THIS<span><a class="mark" href="#errors_err_invalid_this" id="errors_err_invalid_this">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_this" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_this">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used generically to identify that a Node.js API function is called with an
incompatible <code>this</code> value.</p>
<p>Example:</p>
<pre><code class="lang-js">const { URLSearchParams } = require(&apos;url&apos;);
const urlSearchParams = new URLSearchParams(&apos;foo=bar&amp;baz=new&apos;);

const buf = Buffer.alloc(1);
urlSearchParams.has.call(buf, &apos;foo&apos;);
// Throws a TypeError with code &apos;ERR_INVALID_THIS&apos;
</code></pre>
<p><a id="ERR_INVALID_TUPLE"></a></p>
<h3>ERR_INVALID_TUPLE<span><a class="mark" href="#errors_err_invalid_tuple" id="errors_err_invalid_tuple">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_tuple" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_tuple">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an element in the <code>iterable</code> provided to the <a href="url-1.html#url_the_whatwg_url_api" tppabs="http://nodejs.cn/api/en/url.html#url_the_whatwg_url_api">WHATWG</a> <a href="url-1.html#url_constructor_new_urlsearchparams_iterable" tppabs="http://nodejs.cn/api/en/url.html#url_constructor_new_urlsearchparams_iterable"><code>URLSearchParams</code> constructor</a> does not
represent a <code>[name, value]</code> tuple &#x2013; that is, if an element is not iterable, or
does not consist of exactly two elements.</p>
<p><a id="ERR_INVALID_URL"></a></p>
<h3>ERR_INVALID_URL<span><a class="mark" href="#errors_err_invalid_url" id="errors_err_invalid_url">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_url" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_url">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an invalid URL is passed to the <a href="url-1.html#url_the_whatwg_url_api" tppabs="http://nodejs.cn/api/en/url.html#url_the_whatwg_url_api">WHATWG</a>
<a href="url-1.html#url_constructor_new_url_input_base" tppabs="http://nodejs.cn/api/en/url.html#url_constructor_new_url_input_base"><code>URL</code> constructor</a> to be parsed. The thrown error object
typically has an additional property <code>&apos;input&apos;</code> that contains the URL that failed
to parse.</p>
<p><a id="ERR_INVALID_URL_SCHEME"></a></p>
<h3>ERR_INVALID_URL_SCHEME<span><a class="mark" href="#errors_err_invalid_url_scheme" id="errors_err_invalid_url_scheme">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_invalid_url_scheme" tppabs="http://nodejs.cn/api/errors.html#errors_err_invalid_url_scheme">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used generically to signify an attempt to use a URL of an incompatible scheme
(aka protocol) for a specific purpose. It is currently only used in the
<a href="url-1.html#url_the_whatwg_url_api" tppabs="http://nodejs.cn/api/en/url.html#url_the_whatwg_url_api">WHATWG URL API</a> support in the <a href="fs-1.html" tppabs="http://nodejs.cn/api/en/fs.html"><code>fs</code></a> module (which only accepts URLs with
<code>&apos;file&apos;</code> scheme), but may be used in other Node.js APIs as well in the future.</p>
<p><a id="ERR_IPC_CHANNEL_CLOSED"></a></p>
<h3>ERR_IPC_CHANNEL_CLOSED<span><a class="mark" href="#errors_err_ipc_channel_closed" id="errors_err_ipc_channel_closed">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_ipc_channel_closed" tppabs="http://nodejs.cn/api/errors.html#errors_err_ipc_channel_closed">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an attempt is made to use an IPC communication channel that has
already been closed.</p>
<p><a id="ERR_IPC_DISCONNECTED"></a></p>
<h3>ERR_IPC_DISCONNECTED<span><a class="mark" href="#errors_err_ipc_disconnected" id="errors_err_ipc_disconnected">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_ipc_disconnected" tppabs="http://nodejs.cn/api/errors.html#errors_err_ipc_disconnected">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an attempt is made to disconnect an already disconnected IPC
communication channel between two Node.js processes. See the documentation for
the <a href="child_process-1.html" tppabs="http://nodejs.cn/api/en/child_process.html"><code>child_process</code></a> module for more information.</p>
<p><a id="ERR_IPC_ONE_PIPE"></a></p>
<h3>ERR_IPC_ONE_PIPE<span><a class="mark" href="#errors_err_ipc_one_pipe" id="errors_err_ipc_one_pipe">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_ipc_one_pipe" tppabs="http://nodejs.cn/api/errors.html#errors_err_ipc_one_pipe">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an attempt is made to create a child Node.js process using more than
one IPC communication channel. See the documentation for the
<a href="child_process-1.html" tppabs="http://nodejs.cn/api/en/child_process.html"><code>child_process</code></a> module for more information.</p>
<p><a id="ERR_IPC_SYNC_FORK"></a></p>
<h3>ERR_IPC_SYNC_FORK<span><a class="mark" href="#errors_err_ipc_sync_fork" id="errors_err_ipc_sync_fork">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_ipc_sync_fork" tppabs="http://nodejs.cn/api/errors.html#errors_err_ipc_sync_fork">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an attempt is made to open an IPC communication channel with a
synchronous forked Node.js process. See the documentation for the
<a href="child_process-1.html" tppabs="http://nodejs.cn/api/en/child_process.html"><code>child_process</code></a> module for more information.</p>
<p><a id="ERR_MISSING_ARGS"></a></p>
<h3>ERR_MISSING_ARGS<span><a class="mark" href="#errors_err_missing_args" id="errors_err_missing_args">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_missing_args" tppabs="http://nodejs.cn/api/errors.html#errors_err_missing_args">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when a required argument of a Node.js API is not passed. This is currently
only used in the <a href="url-1.html#url_the_whatwg_url_api" tppabs="http://nodejs.cn/api/en/url.html#url_the_whatwg_url_api">WHATWG URL API</a> for strict compliance with the specification
(which in some cases may accept <code>func(undefined)</code> but not <code>func()</code>). In most
native Node.js APIs, <code>func(undefined)</code> and <code>func()</code> are treated identically, and
the <a href="#ERR_INVALID_ARG_TYPE"><code>ERR_INVALID_ARG_TYPE</code></a> error code may be used instead.</p>
<p><a id="ERR_SOCKET_ALREADY_BOUND"></a></p>
<h3>ERR_SOCKET_ALREADY_BOUND<span><a class="mark" href="#errors_err_socket_already_bound" id="errors_err_socket_already_bound">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_socket_already_bound" tppabs="http://nodejs.cn/api/errors.html#errors_err_socket_already_bound">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an attempt is made to bind a socket that has already been bound.</p>
<p><a id="ERR_SOCKET_BAD_PORT"></a></p>
<h3>ERR_SOCKET_BAD_PORT<span><a class="mark" href="#errors_err_socket_bad_port" id="errors_err_socket_bad_port">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_socket_bad_port" tppabs="http://nodejs.cn/api/errors.html#errors_err_socket_bad_port">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an API function expecting a port &gt; 0 and &lt; 65536 receives an invalid
value.</p>
<p><a id="ERR_SOCKET_BAD_TYPE"></a></p>
<h3>ERR_SOCKET_BAD_TYPE<span><a class="mark" href="#errors_err_socket_bad_type" id="errors_err_socket_bad_type">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_socket_bad_type" tppabs="http://nodejs.cn/api/errors.html#errors_err_socket_bad_type">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an API function expecting a socket type (<code>udp4</code> or <code>udp6</code>) receives an
invalid value.</p>
<p><a id="ERR_SOCKET_CANNOT_SEND"></a></p>
<h3>ERR_SOCKET_CANNOT_SEND<span><a class="mark" href="#errors_err_socket_cannot_send" id="errors_err_socket_cannot_send">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_socket_cannot_send" tppabs="http://nodejs.cn/api/errors.html#errors_err_socket_cannot_send">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when data cannot be sent on a socket.</p>
<p><a id="ERR_SOCKET_DGRAM_NOT_RUNNING"></a></p>
<h3>ERR_SOCKET_DGRAM_NOT_RUNNING<span><a class="mark" href="#errors_err_socket_dgram_not_running" id="errors_err_socket_dgram_not_running">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_socket_dgram_not_running" tppabs="http://nodejs.cn/api/errors.html#errors_err_socket_dgram_not_running">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when a call is made and the UDP subsystem is not running.</p>
<p><a id="ERR_STDERR_CLOSE"></a></p>
<h3>ERR_STDERR_CLOSE<span><a class="mark" href="#errors_err_stderr_close" id="errors_err_stderr_close">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_stderr_close" tppabs="http://nodejs.cn/api/errors.html#errors_err_stderr_close">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an attempt is made to close the <code>process.stderr</code> stream. By design,
Node.js does not allow <code>stdout</code> or <code>stderr</code> Streams to be closed by user code.</p>
<p><a id="ERR_STDOUT_CLOSE"></a></p>
<h3>ERR_STDOUT_CLOSE<span><a class="mark" href="#errors_err_stdout_close" id="errors_err_stdout_close">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_stdout_close" tppabs="http://nodejs.cn/api/errors.html#errors_err_stdout_close">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an attempt is made to close the <code>process.stdout</code> stream. By design,
Node.js does not allow <code>stdout</code> or <code>stderr</code> Streams to be closed by user code.</p>
<p><a id="ERR_UNKNOWN_BUILTIN_MODULE"></a></p>
<h3>ERR_UNKNOWN_BUILTIN_MODULE<span><a class="mark" href="#errors_err_unknown_builtin_module" id="errors_err_unknown_builtin_module">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_unknown_builtin_module" tppabs="http://nodejs.cn/api/errors.html#errors_err_unknown_builtin_module">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used to identify a specific kind of internal Node.js error that should not
typically be triggered by user code. Instances of this error point to an
internal bug within the Node.js binary itself.</p>
<p><a id="ERR_UNKNOWN_SIGNAL"></a></p>
<h3>ERR_UNKNOWN_SIGNAL<span><a class="mark" href="#errors_err_unknown_signal" id="errors_err_unknown_signal">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_unknown_signal" tppabs="http://nodejs.cn/api/errors.html#errors_err_unknown_signal">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an invalid or unknown process signal is passed to an API expecting a
valid signal (such as <a href="child_process-1.html#child_process_child_kill_signal" tppabs="http://nodejs.cn/api/en/child_process.html#child_process_child_kill_signal"><code>child.kill()</code></a>).</p>
<p><a id="ERR_UNKNOWN_STDIN_TYPE"></a></p>
<h3>ERR_UNKNOWN_STDIN_TYPE<span><a class="mark" href="#errors_err_unknown_stdin_type" id="errors_err_unknown_stdin_type">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_unknown_stdin_type" tppabs="http://nodejs.cn/api/errors.html#errors_err_unknown_stdin_type">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an attempt is made to launch a Node.js process with an unknown <code>stdin</code>
file type. Errors of this kind cannot <em>typically</em> be caused by errors in user
code, although it is not impossible. Occurrences of this error are most likely
an indication of a bug within Node.js itself.</p>
<p><a id="ERR_UNKNOWN_STREAM_TYPE"></a></p>
<h3>ERR_UNKNOWN_STREAM_TYPE<span><a class="mark" href="#errors_err_unknown_stream_type" id="errors_err_unknown_stream_type">#</a></span></h3><p style="font-size:12px;margin-top:-1em"><a href="errors.html#errors_err_unknown_stream_type" tppabs="http://nodejs.cn/api/errors.html#errors_err_unknown_stream_type">&#x67E5;&#x770B;&#x4E2D;&#x6587;&#x7248;</a></p>
<p>Used when an attempt is made to launch a Node.js process with an unknown
<code>stdout</code> or <code>stderr</code> file type. Errors of this kind cannot <em>typically</em> be caused
by errors in user code, although it is not impossible. Occurrences of this error
are most likely an indication of a bug within Node.js itself.</p>

      </div>
    </div>
  </div>
  <script src="api.js-20170605" tppabs="http://nodejs.cn/static/api.js?20170605"></script>
</body>
</html>